---
title: "Age Analysis"
output: html_document
date: "2026-03-31"
---

```{r}
install.packages("xfun")
library(dplyr)
library(ggplot2)
library(janitor)
library(rstatix)
library(gtsummary)
```
## Age groups

```{r}
freshdata <- freshdata %>%
  mutate(
    Age_group = ifelse(Age >= 37, "Older (≥37)", "Younger (<37)")
  ) %>%
  mutate(Age_group = factor(Age_group, levels = c("Younger (<37)", "Older (≥37)")))
```


```{r}

wilcox.test(No_fertilised ~ Age_group, data = freshdata)

chisq.test(table(freshdata$Protocol_type, freshdata$Age_group))
```
```{r}
ggplot(freshdata, aes(x = Age_group, y = hMG_total_dose)) +
  geom_boxplot(fill = "steelblue") +
  labs(
    title = "Total hMG dose by age group",
    x = "",
    y = "Total hMG dose (IU)"
  ) +
  theme_minimal()
```
```{r}
table(freshdata$Age_group, freshdata$Protocol_type)
table(freshdata$Protocol_type)

ggplot(freshdata, aes(x = Age_group, fill = Protocol_type)) +
  geom_bar(position = "fill") +
  labs(
    title = "Distribution of protocol types by age group",
    x = "",
    y = "Proportion",
    fill = "Protocol type"
  ) +
  theme_minimal()
```
```{r}
df_short <- freshdata %>%
  filter(Protocol_type == "Short Antagonist")

df_short <- df_short %>%
  mutate(
    Optimal_response = ifelse(No_mature_eggs >= 9 & No_mature_eggs <= 15, 1, 0)
  )
```

```{r}
wilcox.test(Age ~ Optimal_response, data = df_short)
wilcox.test(Baseline_AMH ~ Optimal_response, data = df_short)
wilcox.test(Baseline_total_follicles ~ Optimal_response, data = df_short)
wilcox.test(Total_stim_dose ~ Optimal_response, data = df_short)
wilcox.test(FSH_total_dose ~ Optimal_response, data = df_short)
wilcox.test(FSH_avg_daily ~ Optimal_response, data = df_short)
wilcox.test(hMG_total_dose ~ Optimal_response, data = df_short)
```
```{r}
hist(df_short$No_mature_eggs)
```


```{r}
lr1 <- glm(
  Optimal_response ~ Baseline_AMH + Age * Total_stim_dose,
  data = df_short,
  family = binomial
)

summary(lr1)

exp(cbind(OR = coef(lr1), confint(lr1)))
```
```{r}
install.packages("logistf")
library(logistf)
lg1 <- logistf(Optimal_response ~ Age + Baseline_AMH + Total_stim_dose, data = df_short)
summary(lg1)

```

