---
title: "Clustering Analysis"
output: html_document
date: "2026-04-15"
---

```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(VIM)
library(cluster)
library(factoextra)
library(ggplot2)
library(tidyr)
library(caret)
library(RANN)

library(here)
here::here()

freshdata <- read_csv(
  here("data","processed","short_protocol_data.csv"),
  name_repair = "minimal"
)
```

```{r}
cluster_df <- freshdata %>%
  select(
    Unique_number,
    Aetiology_group,
    Age,
    BMI,
    Baseline_AMH,
    Baseline_total_follicles,
    Total_stim_dose,
    GnRH_antagonist_total_dose
  )
```

## KNN imputing missingness pre clustering
```{r}
impute_df <- cluster_df %>%
  select(Age, BMI, Baseline_AMH, Baseline_total_follicles, Total_stim_dose, GnRH_antagonist_total_dose)

imputed <- VIM::kNN(impute_df, k = 5, imp_var = FALSE)

scaled_mat <- scale(imputed)
```

## Silhouette plot
```{r}
sil_width <- c()

for (k in 2:6) {
  pam_fit <- pam(scaled_mat, k = k)
  sil_width[k] <- pam_fit$silinfo$avg.width
}

data.frame(
  k = 2:6,
  mean_silhouette = sil_width[2:6]
)

plot(2:6, sil_width[2:6], type = "b",
     xlab = "Number of clusters (k)",
     ylab = "Mean silhouette width")

pam_fit <- pam(scaled_mat, k = 2)
```

```{r}
cluster_results <- cluster_df %>%
  mutate(cluster = factor(pam_fit$clustering)) %>%
  bind_cols(as.data.frame(imputed) %>% rename_with(~paste0(.x, "_imp")))

table(cluster_results$cluster, cluster_results$Aetiology_group)
prop.table(table(cluster_results$cluster, cluster_results$Aetiology_group), margin = 1)
```
```{r}
cluster_summary <- cluster_results %>%
  group_by(cluster) %>%
  summarise(
    n = n(),
    Age_mean = mean(Age_imp, na.rm = TRUE),
    Age_median = median(Age_imp, na.rm = TRUE),
    BMI_mean = mean(BMI_imp, na.rm = TRUE),
    BMI_median = median(BMI_imp, na.rm = TRUE),
    AMH_mean = mean(Baseline_AMH_imp, na.rm = TRUE),
    AMH_median = median(Baseline_AMH_imp, na.rm = TRUE),
    Follicles_mean = mean(Baseline_total_follicles_imp, na.rm = TRUE),
    Follicles_median = median(Baseline_total_follicles_imp, na.rm = TRUE),
    Total_stim_dose_mean = mean(Total_stim_dose_imp, na.rm = TRUE),
    Total_stim_dose_median = median(Total_stim_dose_imp, na.rm = TRUE),
    GnRH_antagonist_total_dose_mean = mean(GnRH_antagonist_total_dose_imp, na.rm = TRUE),
    GnRH_antagonist_total_dose_median = median(GnRH_antagonist_total_dose_imp, na.rm = TRUE)
  )

cluster_summary
```

```{r}
table(cluster_results$cluster, cluster_results$Aetiology_group)
prop.table(table(cluster_results$cluster, cluster_results$Aetiology_group), margin = 1)
```
```{r}
pca <- prcomp(scaled_mat)

plot_df <- data.frame(
  PC1 = pca$x[, 1],
  PC2 = pca$x[, 2],
  cluster = cluster_results$cluster,
  Aetiology_group = cluster_results$Aetiology_group
)

ggplot(plot_df, aes(PC1, PC2, colour = cluster, shape = Aetiology_group)) +
  geom_point(size = 3, alpha = 0.8) +
  theme_minimal()
```

```{r}
library(dplyr)

cluster_df2 <- freshdata %>%
  select(
    Unique_number,
    Aetiology_group,
    Age,
    BMI,
    Baseline_AMH,
    Baseline_total_follicles,
    FSH_used,
    hMG_used,
    Total_stim_dose,
    GnRH_antagonist_total_dose,
  )

cluster_df2 <- cluster_df2 %>%
  mutate(
    FSH_used = factor(FSH_used),
    hMG_used = factor(hMG_used)
  )

imputed2 <- VIM::kNN(cluster_df2, k=5, imp_var = FALSE)

vars_for_cluster <- cluster_df2 %>%
  select(
    Age,
    BMI,
    Baseline_AMH,
    Baseline_total_follicles,
    FSH_used,
    hMG_used,
    Total_stim_dose,
    GnRH_antagonist_total_dose
  )

imputed2 <- VIM::kNN(vars_for_cluster, k = 5, imp_var = FALSE)

gower_dist <- daisy(imputed2, metric = "gower")
```

```{r}
sil_width <- c()

for (k in 2:6) {
  pam_fit <- pam(gower_dist, k = k, diss = TRUE)
  sil_width[k] <- pam_fit$silinfo$avg.width
}

data.frame(
  k = 2:6,
  mean_silhouette = sil_width[2:6]
)

plot(
  2:6,
  sil_width[2:6],
  type = "b",
  xlab = "Number of clusters (k)",
  ylab = "Mean silhouette width"
)
```
```{r}
pam_fit2 <- pam(gower_dist, k = 3, diss = TRUE)

cluster_results2 <- cluster_df2 %>%
  mutate(cluster = factor(pam_fit2$clustering)) %>%
  bind_cols(
    imputed2 %>% rename_with(~ paste0(.x, "_imp"))
  )

cluster_summary2 <- cluster_results2 %>%
  group_by(cluster) %>%
  summarise(
    n = n(),
    Age_mean = mean(Age_imp, na.rm = TRUE),
    BMI_mean = mean(BMI_imp, na.rm = TRUE),
    AMH_mean = mean(Baseline_AMH_imp, na.rm = TRUE),
    Follicles_mean = mean(Baseline_total_follicles_imp, na.rm = TRUE),
    Total_stim_mean = mean(Total_stim_dose_imp, na.rm = TRUE),
    Antagonist_mean = mean(GnRH_antagonist_total_dose_imp, na.rm = TRUE)
  )

cluster_summary2
```


```{r}
aet_tab2 <- table(cluster_results2$cluster, cluster_results2$Aetiology_group)
aet_tab2
prop.table(aet_tab2, margin = 1)
```

